en:
  languageName: English
  weight: 1

zh-hans:
  languageName: 简体中文
  weight: 4
  params:
    description: 一个快速、响应式和功能丰富的 nitinprajwal 博客主题
    keywords: 'nitinprajwal, Bootstrap, 博客主题'
    archive:
      dateFormat: 01-02
